# PowerShell Script to automatically update photo & video paths for the wedding website
# Run this script whenever you add or remove media files under the ./media/ folders.

$mediaDir = "media"
$outputFile = "media_list.js"

function Get-RelativeFiles($folder) {
    $path = Join-Path $PSScriptRoot "$mediaDir/$folder"
    if (Test-Path $path) {
        $files = Get-ChildItem -Path $path -File | 
                 Where-Object { $_.Extension -match "\.(jpg|jpeg|png|webp|gif|JPG|JPEG|PNG|WEBP)$" } | 
                 Sort-Object Name |
                 Select-Object -ExpandProperty Name
        
        $list = @()
        foreach ($f in $files) {
            $escaped = $f.Replace("'", "\'")
            $list += "        'media/$folder/$escaped'"
        }
        return $list -join ",`n"
    }
    return ""
}

Write-Host "Scanning media folders..."

$retoucheesList = Get-RelativeFiles "photos-retouchees"
$inviteesList = Get-RelativeFiles "photos-invitees"
$normalesList = Get-RelativeFiles "photos-normales"

# Find first video in media/videos/
$videoFile = ""
$videoPath = Join-Path $PSScriptRoot "$mediaDir/videos"
if (Test-Path $videoPath) {
    $video = Get-ChildItem -Path $videoPath -File | 
             Where-Object { $_.Extension -match "\.(mp4|webm|ogv|mov|MP4|WEBM|MOV)$" } | 
             Select-Object -First 1 -ExpandProperty Name
    if ($video) {
        $escapedVideo = $video.Replace("'", "\'")
        $videoFile = "media/videos/$escapedVideo"
    }
}

$jsContent = @"
// Automatically generated by update_media.ps1
// Do not edit manually. Run the PowerShell script to regenerate.
window.MEDIA_DATA = {
    photosRetouchees: [
$retoucheesList
    ],
    photosInvitees: [
$inviteesList
    ],
    photosNormales: [
$normalesList
    ],
    highlightVideo: '$videoFile'
};
"@

# Write content with UTF-8 encoding
[System.IO.File]::WriteAllText((Join-Path $PSScriptRoot $outputFile), $jsContent, [System.Text.Encoding]::UTF8)

Write-Host "media_list.js successfully updated!" -ForegroundColor Green
Write-Host "Retouched photos found: $((Get-ChildItem -Path (Join-Path $PSScriptRoot "$mediaDir/photos-retouchees") -File).Count)"
Write-Host "Guest photos found: $((Get-ChildItem -Path (Join-Path $PSScriptRoot "$mediaDir/photos-invitees") -File).Count)"
Write-Host "Casual photos found: $((Get-ChildItem -Path (Join-Path $PSScriptRoot "$mediaDir/photos-normales") -File).Count)"
Write-Host "Highlight video: $videoFile"
